[workspace]
members = [
    "crates/shebling",
    "crates/shebling-ast",
    "crates/shebling-lexer",
    "crates/shebling-linter",
    "crates/shebling-parser"
]

[workspace.dependencies]
miette = { version = "5.9.0", features = [ "fancy" ]}
thiserror = "1.0.40"
pretty_assertions = "1.3.0"