[workspace]
members = [
    "crates/shebling",
    "crates/shebling-ast",
    "crates/shebling-linter",
    "crates/shebling-parser",
]

[workspace.dependencies]
miette = { version = "5.9.0", features = [ "fancy" ]}