[workspace]
members = [
    "crates/shebling",
    "crates/shebling-ast",
    "crates/shebling-linter",
    "crates/shebling-parser",
    "crates/shebling-parser-old"
]

[workspace.dependencies]
miette = { version = "5.9.0", features = [ "fancy" ]}
thiserror = "1.0.40"
